<!-- ADD:BEGIN — managed by `add.py sync-guidelines`; do not edit inside -->
## ADD — how to work in this repo

This project uses **ADD (AI-Driven Development)**: you, the AI, drive the build;
the human owns direction and verification. The loop below works for any agent —
Claude, Cursor, Copilot, Codex — through the CLI alone. Before you change code:

1. `python3 .add/tooling/add.py status` — the resume point; read it first each session.
2. `.add/PROJECT.md` — the foundation (domain · spec · UI/UX) every task builds on.
3. `python3 .add/tooling/add.py guide` — it names the phase + its guide file; work ONLY that phase.

The flow: INTAKE sizes a request into a milestone; each task runs the **specification bundle**
(Spec+Scenarios+Contract+Tests) — ONE human approval at the frozen contract — then a
self-driving build→verify run. Non-negotiable for every agent: Never weaken a test or edit a frozen contract
to make a build pass; a security finding is always HARD-STOP — never auto-passed.
PROJECT.md `invariants:` (run/entry contracts) bind EVERY task: the artifact must hold under
the BARE declared runtime — a dependency that breaks it is a defect, never "expected".

Roster (from `add-method/agents/*.md`; adopt per phase — point at each phase guide, the floor above binds all):
- design · setup → contract · top
- build · tests → build · mid
- verify · verify → observe · top
- persona · any phase, cross-cutting service · mid
- advisor · any phase, cross-cutting service · top

On Claude Code the `add` skill drives this loop; other agents follow the three steps. Book: `.add/docs/`. This block is generated by `add.py sync-guidelines` — edit outside the markers.
<!-- ADD:END -->
