"""Red suite: a bundle carries the persona routing index, not just the corpus.

`init` vendors the teacher corpus so a standalone bundle can seed personas off-build. But the
corpus is a byte-verbatim third-party snapshot with no routing keys, so the corpus alone does not
tell an agent WHICH lens to reach for. The `use-when:` lives in `personas-index.md`, generated by
`scripts/build_persona_index.py` — and it is only useful to a bundle if the bundle has it.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tooling"))

import add  # noqa: E402


def test_init_vendors_the_persona_index(tmp_path):
    """covers: M1 — a fresh bundle can route to a lens, not merely read the corpus."""
    add.init(tmp_path, "code", "Demo")
    index = tmp_path / "personas-index" / "use-when.md"
    assert index.is_file(), \
        "a bundle vendors the teacher corpus but not its routing index — nothing says which lens to use"
    assert "use-when:" in index.read_text(encoding="utf-8"), \
        "the vendored index carries no `use-when:` routing lines"


def test_the_vendored_index_matches_the_vendored_corpus(tmp_path):
    """covers: M2 — the index describes THIS bundle's corpus, not a different one.

    Every persona the bundle vendors must be findable in the index it vendors alongside. A drift
    here is how an agent gets routed at a lens the bundle does not actually carry.
    """
    add.init(tmp_path, "code", "Demo")
    index_text = (tmp_path / "personas-index" / "use-when.md").read_text(encoding="utf-8")

    vendored = sorted((tmp_path / "personas-teacher").rglob("*.md"))
    personas = [p for p in vendored
                if "description:" in p.read_text(encoding="utf-8", errors="replace")[:600]]
    assert personas, "no personas were vendored at all"

    missing = [p.relative_to(tmp_path / "personas-teacher").with_suffix("").as_posix()
               for p in personas
               if f"`{p.relative_to(tmp_path / 'personas-teacher').with_suffix('').as_posix()}`"
               not in index_text]
    assert not missing, f"{len(missing)} vendored personas are absent from the index, e.g. {missing[:3]}"


def test_the_index_is_not_written_inside_the_vendored_snapshot(tmp_path):
    """covers: R:VENDORFORK — the index must never land inside the verbatim third-party tree.

    `update_teacher.py` replaces `personas-teacher/` wholesale; anything written in there is erased
    on the next refresh, which is exactly why this metadata is a sidecar.
    """
    add.init(tmp_path, "code", "Demo")
    assert not list((tmp_path / "personas-teacher").rglob("use-when.md")), \
        "the routing index was written inside the vendored snapshot — a teacher refresh would erase it"
