"""add_engine.guidelines — the guidelines / CLAUDE.md-injection subsystem (engine-modularization 8/N).

Inject one stable, marker-delimited ADD block into every GUIDELINE_FILES target under the
project root (AGENTS.md, CLAUDE.md, .clinerules). DYNAMIC-BY-REFERENCE: the block tells the
agent to run `add.py status` and read PROJECT.md — it never embeds live state. A closed,
self-contained cluster (4 fns + the cluster-private _INIT_EXCLUDE); transitive-closure AST
scan: ZERO outbound calls to non-cluster add fns. Deps: constants + _atomic_write (io_state)
+ stdlib. None patched.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from add_engine.constants import GUIDELINE_FILES, _GUIDE_BEGIN, _GUIDE_END
from add_engine.io_state import _atomic_write


def _guideline_block() -> str:
    """The canonical ADD block (markers + body, no trailing newline).

    Agent-agnostic by design (v14 agent-portability): the routing steps depend
    only on the CLI and plain files, so any agent — Claude, Cursor, Copilot,
    Codex — can follow them. Claude additionally gets the `add` skill."""
    return (
        f"{_GUIDE_BEGIN}\n"
        "## ADD — how to work in this repo\n"
        "\n"
        "**ADD (AI-Driven Development)** — you, the AI, drive the build; the human owns direction\n"
        "and verification. Works for any agent (Claude · Cursor · Copilot · Codex) through the CLI\n"
        "alone. Before you change code, orient:\n"
        "\n"
        "1. `python3 .add/tooling/add.py status` — the resume point; read it first each session.\n"
        "2. `.add/PROJECT.md` — the read-first foundation (goal · invariants · pointers into `.add/specs/`, the 5-DD standing picture).\n"
        "3. `python3 .add/tooling/add.py guide` — names the current phase + its guide; work ONLY that phase.\n"
        "\n"
        "Flow: INTAKE sizes a request into a milestone; each task drafts the **specification bundle**\n"
        "(Spec · Contract · Tests & Scenarios) to ONE human approval at the frozen contract, then a\n"
        "self-driving build→verify run. Non-negotiable: Never weaken a test or edit a frozen contract\n"
        "to pass a build; a security finding is always HARD-STOP. PROJECT.md `invariants:` bind EVERY\n"
        "task — the artifact must hold under the BARE declared runtime.\n"
        "\n"
        "Roster (`add-method/agents/*.md`): `add-worker` runs each execution beat (direction · build ·\n"
        "verify · persona) and `add-advisor` is the second mind it spawns to plan, pressure-test, or\n"
        "resolve a delegable ambiguity. Each loads the beat's phase guide + the best-fit `.add/personas/`\n"
        "persona — personas carry the expertise, the agent carries the discipline.\n"
        "\n"
        "On Claude Code the `add` skill drives this loop; other agents follow the three steps. Book: https://pilotspace.github.io/ADD/. Generated by `add.py sync-guidelines` — edit outside the markers.\n"
        f"{_GUIDE_END}"
    )


def _inject_block(path: Path) -> str:
    """Write the ADD block into `path`. Returns created|updated|unchanged.

    - unchanged: on-disk block already matches -> no write, no .bak (idempotent).
    - updated:   existing content changes -> back up the original to <path>.bak first.
    - created:   file did not exist -> write the block, no .bak.
    User content outside the markers is always preserved.
    """
    block = _guideline_block()
    if path.exists():
        current = path.read_text(encoding="utf-8")
        begin = current.find(_GUIDE_BEGIN)
        if begin != -1:
            end = current.find(_GUIDE_END, begin)
            if end != -1:                      # replace only the marked region
                end += len(_GUIDE_END)
                new = current[:begin] + block + current[end:]
            else:                              # begin without end: corrupt — append fresh
                print(f"add: warning: {path.name}: found an ADD:BEGIN with no ADD:END "
                      "— appending a fresh block; review the result", file=sys.stderr)
                new = current.rstrip("\n") + "\n\n" + block + "\n"
        else:                                  # no block yet — append, keep user content
            new = current.rstrip("\n") + "\n\n" + block + "\n"
        if new == current:
            return "unchanged"
        _atomic_write(Path(str(path) + ".bak"), current)   # rollback path before mutate
        _atomic_write(path, new)
        return "updated"
    _atomic_write(path, block + "\n")
    return "created"


def _inject_guidelines(project_root: Path) -> list[tuple[str, str]]:
    """Inject the block into each guideline file under `project_root`.

    Symlink-dedup: targets resolving (os.path.realpath) to the same inode are
    written once, against the REAL file (never replacing the symlink with a
    regular file). Per-target OSError is isolated (warn+skip) so one unwritable
    file never aborts the run or `init`.
    """
    results: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name in GUIDELINE_FILES:
        target = project_root / name
        real = os.path.realpath(target)
        if real in seen:
            continue
        seen.add(real)
        write_target = Path(real) if target.is_symlink() else target
        try:
            action = _inject_block(write_target)
        except (OSError, UnicodeDecodeError) as exc:
            # design for failure: an unwritable target OR a non-UTF-8 existing file
            # (e.g. a UTF-16 CLAUDE.md from a Windows editor) must not crash init or
            # abort the other target — warn and skip this one.
            print(f"add: warning: could not sync {name} — {exc}; skipped",
                  file=sys.stderr)
            action = "skipped"
        results.append((name, action))
    return results


# --- commands ----------------------------------------------------------------

_INIT_EXCLUDE = {
    ".add", "AGENTS.md", "CLAUDE.md", ".clinerules", ".git",
    ".gitignore", ".gitattributes", ".github", ".editorconfig",  # VCS/CI/editor scaffolding — no domain signal
    "LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING",            # legal boilerplate — no domain signal
}  # README/docs/source are NOT excluded: they carry domain content adopt.md maps -> brownfield


def _is_brownfield(base: Path) -> bool:
    """True when `base` already holds project content beyond the tool's own scaffolding.

    Judgment-free: a mechanical fact (does the dir hold a non-excluded entry?), so the
    autonomous-onboarding flow knows to map existing code into the living documentation. INTERPRETING
    that code stays with the AI (skill/add/adopt.md) — the engine only detects + signals."""
    if not base.is_dir():
        return False
    return any(child.name not in _INIT_EXCLUDE for child in base.iterdir())
