#!/usr/bin/env python3
"""Build the persona routing index from the vendored teacher corpus.

WHY THIS EXISTS AS A SIDECAR, and not as frontmatter on the personas themselves:
`personas-teacher/` is a pinned, MIT-licensed snapshot of an upstream repository, redistributed
**byte-verbatim** (see `personas-teacher/VENDOR.md` and `THIRD_PARTY_NOTICES.md`).
`scripts/update_teacher.py` replaces that whole tree on refresh and states the contract outright:
"The vendored content is RAW + verbatim — this script never edits an upstream file's contents."

So the `use-when:` routing metadata `personas.md` documents cannot live *inside* those files: it
would fork a third-party snapshot, and the next teacher refresh would silently erase it. It lives
here instead, in a file this project owns and regenerates — derived from each persona's own
`description:`, which every one of them already carries.

`flow:` is deliberately NOT synthesized. Which beats a lens applies to is a judgment call, not
something derivable from a description, and inventing one per persona would be routing metadata
nobody authored. The hand-authored roster in `skill/add/streams.md` remains the place where a
persona is bound to its surfaces.

Usage:  python3 add-method/scripts/build_persona_index.py [--check]
        --check exits non-zero if the committed index is stale (for CI / the test suite).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CORPUS = HERE.parent / "personas-teacher"
# A managed TREE, not a loose file: the installer materializes payload directory-by-directory
# (`MANAGED` + `_clean_replace`), so a lone sibling file would never reach a real install — the
# corpus would land with no way to route into it. `use-when.md` is the routing view; a future
# hand-authored view (e.g. flow.md) would sit beside it.
INDEX_DIR = HERE.parent / "personas-index"
INDEX = INDEX_DIR / "use-when.md"

HEADER = """# Persona routing index

<!-- GENERATED by scripts/build_persona_index.py — do not hand-edit.
     The teacher corpus is a byte-verbatim third-party snapshot, so it carries no routing keys of
     its own; this index is where `use-when:` lives. Regenerate after every teacher refresh. -->

Every persona in the vendored teacher corpus, with the `use-when:` that routes to it. Paths are
relative to `personas-teacher/` in the package, and to `.add/personas-teacher/` in a bundle.
This file itself is vendored to `.add/personas-index/use-when.md`.

`flow:` is not listed: which beats a lens applies to is authored judgment, not something derived
from a description. See the roster in the skill's `streams.md` for personas bound to surfaces.
"""


def _frontmatter(text: str) -> str:
    return text.split("---", 2)[1] if text.startswith("---") else ""


def personas() -> list[tuple[str, str]]:
    """Every corpus persona as `(relative/path/without/suffix, description)`, sorted.

    A corpus file with no `description:` is not a persona (README.md, VENDOR.md, LICENSE); it is
    skipped rather than indexed with an empty routing line.
    """
    found = []
    for path in sorted(CORPUS.rglob("*.md")):
        fm = _frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        match = re.search(r"^description:\s*(.+)$", fm, re.M)
        if not match:
            continue
        rel = path.relative_to(CORPUS).with_suffix("").as_posix()
        found.append((rel, " ".join(match.group(1).strip().strip("\"'").split())))
    return found


def render() -> str:
    entries = personas()
    divisions: dict[str, list[tuple[str, str]]] = {}
    for rel, desc in entries:
        divisions.setdefault(rel.split("/")[0] if "/" in rel else "(root)", []).append((rel, desc))

    out = [HEADER, f"\n{len(entries)} personas across {len(divisions)} divisions.\n"]
    for division in sorted(divisions):
        out.append(f"\n## {division}\n")
        for rel, desc in divisions[division]:
            out.append(f"- `{rel}` — use-when: {desc}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed index is stale")
    args = parser.parse_args()

    fresh = render()
    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
        if current != fresh:
            print(f"{INDEX.name} is stale — regenerate with "
                  f"`python3 add-method/scripts/build_persona_index.py`", file=sys.stderr)
            return 1
        print(f"{INDEX.name} is current ({len(personas())} personas)")
        return 0

    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(fresh, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(HERE.parent.parent)} ({len(personas())} personas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
